// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaxhogijeadparckdaub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlheGhvZ2lqZWFkcGFyY2tkYXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDE2NTAsImV4cCI6MjA2NjYxNzY1MH0.KVreqJbd_eNnyUWW_btdFh_WdnKEV_CYGTrNfykMQew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);