
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { SavedResult } from '@/contexts/SimulationHistoryContext';
import { formatCurrency, formatPercentage } from '@/lib/utils';

export const generatePDF = async (result: SavedResult): Promise<void> => {
  const filename = prompt('Enter filename for PDF:', `${result.name}_report.pdf`);
  if (!filename) return;

  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPosition = 20;

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(66, 139, 202);
  pdf.text('Retirement Simulation Report', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  // Subtitle
  pdf.setFontSize(16);
  pdf.setTextColor(108, 117, 125);
  pdf.text(result.name, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 10;

  pdf.setFontSize(12);
  pdf.text(`Generated on ${result.timestamp.toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  // Key Metrics Section
  pdf.setFontSize(18);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Key Results', 20, yPosition);
  yPosition += 10;

  const metrics = [
    ['Success Probability', formatPercentage(result.results.summary.goal_probability)],
    ['Median Wealth at Retirement', formatCurrency(result.results.summary.median)],
    ['Best Case (90th percentile)', formatCurrency(result.results.summary.percentile_90)],
    ['Worst Case (10th percentile)', formatCurrency(result.results.summary.percentile_10)],
    ['Portfolio Volatility', formatPercentage(result.results.summary.volatility)],
    ['Maximum Drawdown', `-${formatPercentage(result.results.summary.max_drawdown)}`],
    ['Value at Risk (95%)', formatCurrency(result.results.summary.var_5)],
    ['Conditional VaR', formatCurrency(result.results.summary.cvar_5)],
  ];

  pdf.setFontSize(11);
  pdf.setTextColor(80, 80, 80);

  metrics.forEach(([label, value]) => {
    pdf.text(`${label}:`, 25, yPosition);
    pdf.setFont(undefined, 'bold');
    pdf.text(value, 120, yPosition);
    pdf.setFont(undefined, 'normal');
    yPosition += 7;
  });

  yPosition += 10;

  // Input Parameters Section
  pdf.setFontSize(18);
  pdf.setTextColor(40, 40, 40);
  pdf.text('Simulation Parameters', 20, yPosition);
  yPosition += 10;

  const inputs = [
    ['Current Age', `${result.inputs.age} years`],
    ['Retirement Age', `${result.inputs.retirement_age} years`],
    ['Years to Retirement', `${result.inputs.retirement_age - result.inputs.age} years`],
    ['Initial Savings', formatCurrency(result.inputs.savings)],
    ['Annual Contribution', formatCurrency(result.inputs.contribution)],
    ['Expected Annual Return', formatPercentage(result.inputs.return_rate)],
    ['Portfolio Volatility', formatPercentage(result.inputs.volatility)],
    ['Retirement Goal', formatCurrency(result.inputs.goal)],
    ['Number of Simulations', result.inputs.num_simulations.toLocaleString()],
  ];

  pdf.setFontSize(11);
  pdf.setTextColor(80, 80, 80);

  inputs.forEach(([label, value]) => {
    pdf.text(`${label}:`, 25, yPosition);
    pdf.setFont(undefined, 'bold');
    pdf.text(value, 120, yPosition);
    pdf.setFont(undefined, 'normal');
    yPosition += 7;
  });

  // Footer
  pdf.setFontSize(10);
  pdf.setTextColor(150, 150, 150);
  pdf.text('Generated by Capital Forecast', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  pdf.save(filename.endsWith('.pdf') ? filename : `${filename}.pdf`);
};
